
# Medicaid thresholds by FPL for each state. If fpl_income is less than the state floor, redirect user to medicaid resources
alabama = Medicaid.find_or_create_by(state: 'alabama', fpl_floor: 0.18)
alaska = Medicaid.find_or_create_by(state: 'alaska', fpl_floor: 1.34)
arizona = Medicaid.find_or_create_by(state: 'arizona', fpl_floor: 1.38)
arkansas = Medicaid.find_or_create_by(state: 'arkansas', fpl_floor: 1.38)
california = Medicaid.find_or_create_by(state: 'california', fpl_floor: 1.38)
colorado = Medicaid.find_or_create_by(state: 'colorado', fpl_floor: 1.38)
connecticut = Medicaid.find_or_create_by(state: 'connecticut', fpl_floor: 2.01)
doc = Medicaid.find_or_create_by(state: 'district of columbia', fpl_floor: 2.21)
florida = Medicaid.find_or_create_by(state: 'florida', fpl_floor: 0.35)
georgia = Medicaid.find_or_create_by(state: 'georgia', fpl_floor: 0.40)
hawaii = Medicaid.find_or_create_by(state: 'hawaii', fpl_floor: 1.38)
idaho = Medicaid.find_or_create_by(state: 'idaho', fpl_floor: 0.29)
illinois = Medicaid.find_or_create_by(state: 'illinois', fpl_floor: 1.38)
indiana = Medicaid.find_or_create_by(state: 'indiana', fpl_floor: 0.25)
iowa = Medicaid.find_or_create_by(state: 'iowa', fpl_floor: 1.38)
kansas = Medicaid.find_or_create_by(state: 'kansas', fpl_floor: 0.38)
kentucky = Medicaid.find_or_create_by(state: 'kentucky', fpl_floor: 1.38)
louisiana = Medicaid.find_or_create_by(state: 'louisiana', fpl_floor: 0.24)
maine = Medicaid.find_or_create_by(state: 'maine', fpl_floor: 1.05)
maryland = Medicaid.find_or_create_by(state: 'maryland', fpl_floor: 1.38)
massachusetts = Medicaid.find_or_create_by(state: 'massachusetts', fpl_floor: 1.38)
michigan = Medicaid.find_or_create_by(state: 'michigan', fpl_floor: 1.38)
minnesota = Medicaid.find_or_create_by(state: 'minnesota', fpl_floor: 2.05)
mississippi = Medicaid.find_or_create_by(state: 'mississippi', fpl_floor: 0.27)
missouri = Medicaid.find_or_create_by(state: 'missouri', fpl_floor: 0.23)
montana = Medicaid.find_or_create_by(state: 'montana', fpl_floor: 0.52)
nebraska = Medicaid.find_or_create_by(state: 'nebraska', fpl_floor: 0.62)
nevada = Medicaid.find_or_create_by(state: 'nevada', fpl_floor: 1.38)
new_hampshire = Medicaid.find_or_create_by(state: 'new hampshire', fpl_floor: 1.38)
new_jersey = Medicaid.find_or_create_by(state: 'new jersey', fpl_floor: 1.38)
new_mexico = Medicaid.find_or_create_by(state: 'new mexico', fpl_floor: 1.38)
new_york = Medicaid.find_or_create_by(state: 'new york', fpl_floor: 1.38)
north_carolina = Medicaid.find_or_create_by(state: 'north carolina', fpl_floor: 0.50)
north_dakota = Medicaid.find_or_create_by(state: 'north dakota', fpl_floor: 1.38)
ohio = Medicaid.find_or_create_by(state: 'ohio', fpl_floor: 1.38)
oklahoma = Medicaid.find_or_create_by(state: 'oklahoma', fpl_floor: 0.47)
oregon = Medicaid.find_or_create_by(state: 'oregon', fpl_floor: 1.38)
pennsylvania = Medicaid.find_or_create_by(state: 'pennsylvania', fpl_floor: 1.38)
rhode_island = Medicaid.find_or_create_by(state: 'rhode island', fpl_floor: 1.38)
south_carolina = Medicaid.find_or_create_by(state: 'south carolina', fpl_floor: 0.67)
south_dakota = Medicaid.find_or_create_by(state: 'south dakota', fpl_floor: 0.63)
tennessee = Medicaid.find_or_create_by(state: 'new hampshire', fpl_floor: 1.33)
texas = Medicaid.find_or_create_by(state: 'texas', fpl_floor: 0.20)
utah = Medicaid.find_or_create_by(state: 'utah', fpl_floor: 0.56)
vermont = Medicaid.find_or_create_by(state: 'vermont', fpl_floor: 1.38)
virginia = Medicaid.find_or_create_by(state: 'virginia', fpl_floor: 0.54)
washington = Medicaid.find_or_create_by(state: 'washington', fpl_floor: 1.38)
west_virginia = Medicaid.find_or_create_by(state: 'west virginia', fpl_floor: 1.38)
wisconsin = Medicaid.find_or_create_by(state: 'wisconsin', fpl_floor: 1.00)
wyoming = Medicaid.find_or_create_by(state: 'wyoming', fpl_floor: 0.61)




