
# Medicaid thresholds by FPL for each state. If fpl_income is less than the state floor, redirect user to medicaid resources
alabama = Medicaid.find_or_create_by(state: 'al', fpl_floor: 0.18)
alaska = Medicaid.find_or_create_by(state: 'ak', fpl_floor: 1.34)
arizona = Medicaid.find_or_create_by(state: 'az', fpl_floor: 1.38)
arkansas = Medicaid.find_or_create_by(state: 'ar', fpl_floor: 1.38)
california = Medicaid.find_or_create_by(state: 'ca', fpl_floor: 1.38)
colorado = Medicaid.find_or_create_by(state: 'co', fpl_floor: 1.38)
connecticut = Medicaid.find_or_create_by(state: 'ct', fpl_floor: 2.01)
dc = Medicaid.find_or_create_by(state: 'dc', fpl_floor: 2.21)
florida = Medicaid.find_or_create_by(state: 'fl', fpl_floor: 0.35)
georgia = Medicaid.find_or_create_by(state: 'ga', fpl_floor: 0.40)
hawaii = Medicaid.find_or_create_by(state: 'hi', fpl_floor: 1.38)
idaho = Medicaid.find_or_create_by(state: 'id', fpl_floor: 0.29)
illinois = Medicaid.find_or_create_by(state: 'il', fpl_floor: 1.38)
indiana = Medicaid.find_or_create_by(state: 'in', fpl_floor: 0.25)
iowa = Medicaid.find_or_create_by(state: 'ia', fpl_floor: 1.38)
kansas = Medicaid.find_or_create_by(state: 'ks', fpl_floor: 0.38)
kentucky = Medicaid.find_or_create_by(state: 'ky', fpl_floor: 1.38)
louisiana = Medicaid.find_or_create_by(state: 'la', fpl_floor: 0.24)
maine = Medicaid.find_or_create_by(state: 'me', fpl_floor: 1.05)
maryland = Medicaid.find_or_create_by(state: 'md', fpl_floor: 1.38)
massachusetts = Medicaid.find_or_create_by(state: 'ma', fpl_floor: 1.38)
michigan = Medicaid.find_or_create_by(state: 'mi', fpl_floor: 1.38)
minnesota = Medicaid.find_or_create_by(state: 'mn', fpl_floor: 2.05)
mississippi = Medicaid.find_or_create_by(state: 'ms', fpl_floor: 0.27)
missouri = Medicaid.find_or_create_by(state: 'mo', fpl_floor: 0.23)
montana = Medicaid.find_or_create_by(state: 'mt', fpl_floor: 0.52)
nebraska = Medicaid.find_or_create_by(state: 'ne', fpl_floor: 0.62)
nevada = Medicaid.find_or_create_by(state: 'nv', fpl_floor: 1.38)
new_hampshire = Medicaid.find_or_create_by(state: 'nh', fpl_floor: 1.38)
new_jersey = Medicaid.find_or_create_by(state: 'nj', fpl_floor: 1.38)
new_mexico = Medicaid.find_or_create_by(state: 'nm', fpl_floor: 1.38)
new_york = Medicaid.find_or_create_by(state: 'ny', fpl_floor: 1.38)
north_carolina = Medicaid.find_or_create_by(state: 'nc', fpl_floor: 0.50)
north_dakota = Medicaid.find_or_create_by(state: 'nd', fpl_floor: 1.38)
ohio = Medicaid.find_or_create_by(state: 'oh', fpl_floor: 1.38)
oklahoma = Medicaid.find_or_create_by(state: 'ok', fpl_floor: 0.47)
oregon = Medicaid.find_or_create_by(state: 'or', fpl_floor: 1.38)
pennsylvania = Medicaid.find_or_create_by(state: 'pa', fpl_floor: 1.38)
rhode_island = Medicaid.find_or_create_by(state: 'ri', fpl_floor: 1.38)
south_carolina = Medicaid.find_or_create_by(state: 'sc', fpl_floor: 0.67)
south_dakota = Medicaid.find_or_create_by(state: 'sd', fpl_floor: 0.63)
tennessee = Medicaid.find_or_create_by(state: 'tn', fpl_floor: 1.33)
texas = Medicaid.find_or_create_by(state: 'tx', fpl_floor: 0.20)
utah = Medicaid.find_or_create_by(state: 'ut', fpl_floor: 0.56)
vermont = Medicaid.find_or_create_by(state: 'vt', fpl_floor: 1.38)
virginia = Medicaid.find_or_create_by(state: 'va', fpl_floor: 0.54)
washington = Medicaid.find_or_create_by(state: 'wa', fpl_floor: 1.38)
west_virginia = Medicaid.find_or_create_by(state: 'wv', fpl_floor: 1.38)
wisconsin = Medicaid.find_or_create_by(state: 'wi', fpl_floor: 1.00)
wyoming = Medicaid.find_or_create_by(state: 'wy', fpl_floor: 0.61)




