rake db:seed:make_users
rake db:seed:make_navbar_entries
rake db:seed:add_zips
rake db:seed:make_cms_data
rake db:seed:make_cpt_code_maps
rake db:seed:make_rating_areas
rake db:seed:make_specialty_drugs
rake db:seed:make_plans_hc_1
rake db:seed:make_plans_hc_2
rake db:seed:make_plans_hc_3
rake db:seed:make_plans_hc_4
rake db:seed:make_plans_hc_5
rake db:seed:make_plans_hc_6
rake db:seed:make_plans_hc_7
rake db:seed:make_plans_hc_8
rake db:seed:make_plans_rwjf_1    
rake db:seed:make_fpl_table
rake db:seed:make_cap_table
rake db:seed:make_medicaid_table
rake db:seed:make_plan_url_maps
