heroku run rake db:seed:make_users
heroku run rake db:seed:make_navbar_entries
heroku run rake db:seed:add_zips
heroku run rake db:seed:make_cms_data
heroku run rake db:seed:make_cpt_code_maps
heroku run rake db:seed:make_rating_areas
heroku run rake db:seed:make_specialty_drugs
heroku run rake db:seed:make_plans_hc_1
heroku run rake db:seed:make_plans_hc_2
heroku run rake db:seed:make_plans_hc_3
heroku run rake db:seed:make_plans_hc_4
heroku run rake db:seed:make_plans_hc_5
heroku run rake db:seed:make_plans_hc_6
heroku run rake db:seed:make_plans_hc_7
heroku run rake db:seed:make_plans_hc_8
heroku run rake db:seed:make_plans_rwjf_1    
