octreotide acetate	SANDOSTATIN	ACROMEGALY
Sandostatin LAR		ACROMEGALY
Somatuline Depot		ACROMEGALY
Somavert		ACROMEGALY

Vivitrol		ALCOHOL / OPIOID DEPENDENCY
		
Oralair		ALLERGEN IMMUNOTHERAPY
		
Xolair		ALLERGIC ASTHMA
		
Aralast		ALPHA-1 ANTITRYPSIN DEFICIENCY
Glassia		ALPHA-1 ANTITRYPSIN DEFICIENCY
Zemaira		ALPHA-1 ANTITRYPSIN DEFICIENCY
		
Aranesp		ANEMIA
Epogen		ANEMIA
Procrit		ANEMIA
		
Botox		BOTULINUM TOXINS
Dysport		BOTULINUM TOXINS
Myobloc		BOTULINUM TOXINS
Xeomin		BOTULINUM TOXINS
		
Tikosyn		CARDIAC DISORDERS
		
Implanon		COAGULATION DISORDERS
Mirena		
Nexplanon		
Skyla		
		
Arcalyst		ASSOCIATED PERIODIC SYNDROMES
Ilaris		
		
Bethkis		CYSTIC FIBROSIS
Kalydeco		CYSTIC FIBROSIS
Pulmozyme		CYSTIC FIBROSIS
TOBI Podhaler		CYSTIC FIBROSIS
tobramycin nebulizer 	TOBI	CYSTIC FIBROSIS
		
Xiaflex		DUPUYTREN